advcbv/advcbv/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # func way
    # path('', views.index, name='index'),

    # SIMPLE CBV way
    # path('', views.CBView.as_view()),

    # CBVs TemplateView
    path('', views.IndexView.as_view()),
    path('basic_app/', include('basic_app.urls', namespace='basic_app')),
]

advcbv/basic_app/urls.py
from django.urls import path
# from django.conf.urls import url
from . import views

app_name = 'basic_app'

urlpatterns = [
    path('', views.SchoolListView.as_view(), name='list'),
    # url(r'^(?P<pk>[-\w]+)/$', views.SchoolDetailView.as_view(), name='detail'),
    path('<int:pk>/', views.SchoolDetailView.as_view(), name='detail'),
    path('create/', views.SchoolCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.SchoolUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.SchoolDeleteView.as_view(), name='delete'),
    path('create_student/', views.StudentCreateView.as_view(), name='create_student'),
    path('update_student/<int:pk>/', views.StudentUpdateView.as_view(), name='update_student'),
    path('delete_student/<int:pk>/', views.StudentDeleteView.as_view(), name='delete_student'),
]

advcbv/basic_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('basic_app:detail', kwargs={'pk':self.pk})

class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name='students', on_delete=models.PROTECT)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('basic_app:detail', kwargs={'pk':self.school.pk})

advcbv/basic_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import models
from django.urls import reverse_lazy
# CBV Import
from django.views.generic import (View, TemplateView,
                                  ListView, DetailView,
                                  CreateView, UpdateView,
                                  DeleteView)

# Create your views here.

# normal function way to do this
# def index(request):
#     return render(request, 'index.html')

# SIMPLE CBV(Class Base Views) way to do this
# class CBView(View):
#     def get(self, request):
#         return HttpResponse('CLASS BASED VIEWS ARE COOL!')

# CBVs and TemplateView
class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['injectme'] = 'BASIC INJECTION!'
        return context


class SchoolListView(ListView):
    model = models.School
    # ListView returns school_list
    # do this if you want your own name for that school_list
    context_object_name = 'schools'


class SchoolDetailView(DetailView):
    # DetailView returns school
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'basic_app/school_detail.html'


class SchoolCreateView(CreateView):
    fields = ('name', 'principal', 'location')
    model = models.School


class SchoolUpdateView(UpdateView):
    fields = ('name', 'principal')
    model = models.School


class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy('basic_app:list')


class StudentCreateView(CreateView):
    fields = ('name', 'age', 'school')
    model = models.Student

class StudentUpdateView(UpdateView):
    fields = ('name', 'age', 'school')
    model = models.Student

class StudentDeleteView(DeleteView):
    model = models.Student
    success_url = reverse_lazy('basic_app:list')
    # kwargs={'pk':model.school}

advcbv/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar navbar-dark bg-primary">
      <div class="container">
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'basic_app:list' %}">Schools</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href=""></a>
              </li>
            </ul>
          </div>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
      {% endblock  %}
    </div>
  </body>
</html>

advcbv/basic_app/templates/basic_app/school_confirm_delete.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}
<h1>Delete {{school.name}}?</h1>
<form method="post">
  {% csrf_token %}
  <input type="submit" class='btn btn-danger' value="Delete">
  <a href="{% url 'basic_app:detail' pk=school.pk %}">Cancel</a>
</form>
{% endblock  %}

advcbv/basic_app/templates/basic_app/school_detail.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}
<div class="jumbotron">
  <h1>Welcome to School Detail Page!</h1>
  <h2>School Details: </h2>
  <p>Name: {{school_detail.name}}</p>
  <p>principal: {{school_detail.principal}}</p>
  <p>location: {{school_detail.location}}</p>
  <h3>Students:</h3>
  {% for student in school_detail.students.all %}
    <p>
      {{student.name}} who is {{student.age}} years old.
      <a class='btn btn-warning' href="{% url 'basic_app:update_student' pk=student.pk %}">Update</a>
      <a class='btn btn-danger' href="{% url 'basic_app:delete_student' pk=student.pk %}">Delete</a>
    </p>
  {% endfor %}
</div>
<div class="container">
  <p><a class='btn btn-warning' href="{% url 'basic_app:update' pk=school_detail.pk %}">Update</a></p>
  <p><a class='btn btn-danger' href="{% url 'basic_app:delete' pk=school_detail.pk %}">Delete</a></p>
</div>
{% endblock %}

advcbv/basic_app/templates/basic_app/school_form.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}
<h1>
  {% if not form.instance.pk %}
      Create School
  {% else %}
      Update School
  {% endif %}
</h1>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" class="btn btn-primary" value="Submit">
</form>

{% endblock %}

advcbv/basic_app/templates/basic_app/school_list.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}
<h1>Welcome to a list of all the schools!</h1>
<ol>
  {% for school in schools %}
    <h2><li><a href="{{school.id}}">{{school.name}}</a></li></h2>
  {% endfor %}
</ol>
<a class='btn btn-primary' href="{% url 'basic_app:create' %}">Create School</a>
<a class='btn btn-primary' href="{% url 'basic_app:create_student' %}">Create Student</a>
{% endblock %}

advcbv/basic_app/templates/basic_app/student_confirm_delete.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}
<h1>Delete {{student.name}}?</h1>
<form method="post">
  {% csrf_token %}
  <input type="submit" class='btn btn-danger' value="Delete">
  <a href="{% url 'basic_app:list' %}">Cancel</a>
</form>
{% endblock  %}

advcbv/basic_app/templates/basic_app/student_form.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}
<h1>
  {% if not form.instance.pk %}
      Create Student
  {% else %}
      Update Student
  {% endif %}
</h1>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" class="btn btn-primary" value="Submit">
</form>

{% endblock %}

advcbv/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar navbar-dark bg-primary">
      <div class="container">
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'basic_app:list' %}">Schools</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href=""></a>
              </li>
            </ul>
          </div>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
      {% endblock  %}
    </div>
  </body>
</html>

advcbv/templates/index.html
{% extends "base.html" %}
{% block body_block %}

  <div class="jumbotron">
    <h1>Home Page!</h1>
    <h1>Testing TemplateView</h1>
    <h2>Injected content: {{ injectme }}</h2>
  </div>
{% endblock  %}